In [4]:
import numpy as np
# Create an array from 1 to 20
arr = np.arange(1, 21)
print("Array:")
print(arr)
# 2. Find the shape of the array
print(arr.shape)
# 3. Find the maximum and minimum values
print(arr.max())
print(arr.min())
# 4. Calculate the mean and standard deviation
print(arr.mean())
print(arr.std())
# 5. Reshape the array into a 4 x 5 matrix
print("Reshaped Matrix:")
matrix = arr.reshape(4, 5)
print(matrix)
# 6. Display the second row
print("Second Row:")
print(matrix[1])
# 7. Display the third column
print("Third Column:")
print(matrix[:, 2])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
20
1
10.5
5.766281297335398
Reshaped Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Second Row:
[ 6  7  8  9 10]
Third Column:
[ 3  8 13 18]


In [5]:
import numpy as np
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print("\nSum of elements in A:")
print(A.sum())

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]

Sum of elements in A:
150


In [6]:
import pandas as pd
data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Kiran", "Anu", "Sita"],
    "Marks": [85, 92, 78, 88, 95]
}
df = pd.DataFrame(data)
print("Student Data:")
print(df)

print("\nFirst Three Records:")
print(df.head(3))

print("\nAverage Marks:")
print(df["Marks"].mean())

print("\nStudent with Highest Marks:")
highest = df["Marks"].max()
print(df[df["Marks"] == highest])

print("\nStudent with Lowest Marks:")
print(df[df["Marks"] == df["Marks"].min()])

grade = []

for marks in df["Marks"]:
    if marks >= 90:
        grade.append("A")
    elif marks >= 80:
        grade.append("B")
    else:
        grade.append("C")
df["Grade"] = grade
print("\nDataFrame with Grade:")
print(df)

Student Data:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

First Three Records:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average Marks:
87.6

Student with Highest Marks:
   Roll No  Name  Marks
4      105  Sita     95

Student with Lowest Marks:
   Roll No   Name  Marks
2      103  Kiran     78

DataFrame with Grade:
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [7]:
import pandas as pd
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
}
df = pd.DataFrame(data)
df["Total Value"] = df["Price"] * df["Quantity"]
print("DataFrame:")
print(df)

print("\nProduct with Highest Total Value:")
print(df[df["Total Value"] == df["Total Value"].max()])

print("\nOverall Inventory Value:")
print(df["Total Value"].sum())

DataFrame:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Product with Highest Total Value:
  Product  Price  Quantity  Total Value
0  Laptop  50000        10       500000

Overall Inventory Value:
711000


In [13]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# Add the Class column
df["Class"] = iris.target
df.columns = ["Sepal_L", "Sepal_W", "Petal_L", "Petal_W", "Class"]
print("Iris DataFrame:")
print(df)

print("\nFirst Five Records:")
print(df.head())

print("\nShape of the DataFrame:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSummary Statistics:")
print(df.describe())

print("\nSamples in Each Class:")
print(df["Class"].value_counts())

Iris DataFrame:
     Sepal_L  Sepal_W  Petal_L  Petal_W  Class
0        5.1      3.5      1.4      0.2      0
1        4.9      3.0      1.4      0.2      0
2        4.7      3.2      1.3      0.2      0
3        4.6      3.1      1.5      0.2      0
4        5.0      3.6      1.4      0.2      0
..       ...      ...      ...      ...    ...
145      6.7      3.0      5.2      2.3      2
146      6.3      2.5      5.0      1.9      2
147      6.5      3.0      5.2      2.0      2
148      6.2      3.4      5.4      2.3      2
149      5.9      3.0      5.1      1.8      2

[150 rows x 5 columns]

First Five Records:
   Sepal_L  Sepal_W  Petal_L  Petal_W  Class
0      5.1      3.5      1.4      0.2      0
1      4.9      3.0      1.4      0.2      0
2      4.7      3.2      1.3      0.2      0
3      4.6      3.1      1.5      0.2      0
4      5.0      3.6      1.4      0.2      0

Shape of the DataFrame:
(150, 5)

Column Names:
Index(['Sepal_L', 'Sepal_W', 'Petal_L', 'Petal_W', 'Clas